<?php
/**
 * Footer template part.
 *
 * 🚫🚫🚫
 * DO NOT EDIT THIS FILE WHILE INSIDE THE PLUGIN! Changes You make will be lost when a new version
 * of the AMP plugin is released. You need to copy this file out of the plugin and put it into your
 * custom theme, for example. To learn about how to customize these Reader-mode AMP templates, please
 * see: https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/
 * 🚫🚫🚫
 *
 * @package AMP
 */

/**
 * Context.
 *
 * @var AMP_Post_Template $this
 */
?>
<footer class="amp-wp-footer">
	<div class="amp-ri-logo">
		<a href="<?php echo esc_url( $this->get( 'home_url' ) ); ?>">
	    	<span class="amp-site-title">
				<?php echo esc_html( wptexturize( $this->get( 'blog_name' ) ) ); ?>
			</span>
	    </a>
	</div>
	<div class="copyright">
		<p class="addr">Montes Urales No. 425 Col. Lomas de Chapultepec México, Ciudad de México, C.P. 11000.</p>
		<p>Todos los Derechos Reservados.</p>
		<p>Capital Media. Copyright © 2020.</p>
	</div>
</footer>
